Disable the rendering of emojis in Markdown
mezzio/mezzio-tooling pull request #26
Opened 2022-06-01 19:46 UTC by ghostwriter

|    Q          |   A
|-------------- | ------
| QA            | yes

2022-06-01 19:58 UTC, rieschl approved these changes

2022-06-01 20:09 UTC, froschdesign requested changes

2022-06-01 20:09 UTC, froschdesign commented on README.md
> +- **`mezzio:action:create`**: Create an action class file; this is an alias for the `mezzio:handler:create` command, listed below.
To ignore the Markdown formatting [a backslash must be used](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#ignoring-markdown-formatting) but for [commands](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) the single backticks are correct.
So please remove the text styling for bold here.

Thanks in advance! 👍

2022-08-10 08:16 UTC, Ocramius approved these changes
Thanks @ghostwriter!

2022-08-10 08:16 UTC, merged