Refine routes list functionality
mezzio/mezzio-tooling pull request #58
Opened 2024-11-14 11:55 UTC by settermjd

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR implements all but one of the suggestions that @gsteel made in #52. Thank you for the motivation and inspiration to make the changes and improve the original work.

2024-11-14 12:00 UTC, settermjd commented
I don't know if I've messed this PR up a little, given the number of commits.

2024-11-20 06:21 UTC, alexmerlin commented
> I don't know if I've messed this PR up a little, given the number of commits. Also, the Psalm results I have locally are different from the GitHub check results. Would love some help getting them in sync.

@settermjd Try running Psalm locally without cache:
```shell
vendor/bin/psalm --no-cache
```
Or explicitly clear cache first:
```shell
vendor/bin/psalm --clear-cache
```
before running Psalm as usually.

2024-11-20 11:08 UTC, gsteel requested changes
Sorry @settermjd - I've got quite a lot of feedback here 😬

Overall, I think a lot of this can be simplified.

2024-11-20 11:08 UTC, gsteel commented on src/ConfigProvider.php
> +                ConfigLoaderInterface::class                    => DefaultRoutesConfigLoaderFactory::class,
The factory should be mapped to the implementation, i.e. `RoutesFileLoader::class => Factory::class` and the interface should be added to `aliases`, i.e. `ConfigLoaderInterface::class => RoutesFileLoader::class`,

Users then do the same thing with `'factories' => [MyLoader::class => MyFactory::class], 'aliases' => [ConfigLoaderInterface::class => MyLoader::class]`

The difference is that I can ask the container for a specific implementation, or, I can ask it for the configured, default implementation by using the interface

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptions.php
> +            array_walk($methods, fn(string &$value) => $value = strtoupper($value));
```suggestion
            $this->methods = array_map(static fn (string $value): string => strtoupper($value), $methods);
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptions.php
> +        private array|string|null $methods
I would drop `null|string` from `$methods` and make the argument `list<string>`, so you always have either `list<string>` or `[]`

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptionsInterface.php
> +    public function getMethods(): array|string|null;
```suggestion
    /**
     * Returns any route methods to filter the available routing data by
     *
     * @return list<string>
     */
    public function getMethods(): array;
```

2024-11-20 11:08 UTC, gsteel commented on README.md
> +- _config/routes.php_
First emphasis style on the page wins, so either change all the others to `_` or adjust your changes to use `*`

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +    public function getFilterOptions(): RouteFilterOptionsInterface
Do we need a getter for the options? If it is unused in `src`, let's drop it.

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptionsInterface.php
> +    public function has(string $filterOption): bool;
The `has` method seems unnecessary when consumers can test for `$options->getMiddleware() === []` or `$options->getName() === null`

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        if ($this->filterOptions->has("name")) {
```suggestion
        if ($this->filterOptions->getName() !== null) {
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        if ($this->filterOptions->has("path")) {
```suggestion
        if ($this->filterOptions->getPath() !== null) {
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        if ($this->filterOptions->has("middleware")) {
```suggestion
        if ($this->filterOptions->getMiddleware() !== null) {
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        if ($this->filterOptions->has("methods")) {
```suggestion
        if ($this->filterOptions->getMethods() !== []) {
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +
Because this method is private and the argument is annotated as 'name'|'path', this conditional is unnecessary

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +            $path = $this->filterOptions->getPath();
```suggestion
            $path = $this->filterOptions->getPath();
            assert($path !== null);
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +            sprintf("/%s/", $this->filterOptions->getName()),
```suggestion
            $name = $this->filterOptions->getName();
            assert($name !== null);
            sprintf("/%s/", $name),
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        $methods = $this->filterOptions->getMethods() ?? [];
This null check will be unnecessary if the interface always returns an array

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +            is_string($methods) ? [$methods] : $methods,
And this ternary could be dropped too

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
> +        $matchesMiddleware = $this->filterOptions->getMiddleware() ?? "";
```suggestion
        $matchesMiddleware = $this->filterOptions->getMiddleware();
        assert($matchesMiddleware !== null);
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RoutesFilter.php
>          try {
I'm not convinced that any of this needs wrapping in try/catch… unless it's an invalid pattern I guess - but you could use `preg_quote` on the argument?

2024-11-20 11:08 UTC, gsteel commented on src/Routes/ListRoutesCommand.php
> +            [strtolower((string) $input->getOption('supports-method'))],
You should check all of these values against the empty string and coalesce to null in that case. And why `strtolower` everything? It's possible that the Route values are mixed case and the RoutesFilter does not `strtolower` those.

```php
$middlewareOption = $input->getOption('has-middleware');
$middlewareOption = ! is_string($middlewareOption) || $middlewareOption === '' ? null : $middlewareOption;
```

2024-11-20 11:08 UTC, gsteel commented on src/Routes/ListRoutesCommand.php
> +    private function getRows(bool $requireNames = false): array
```suggestion
    private function getRows(RouteFilterOptions $options, bool $requireNames = false): array
```

Passing filter options as an argument negates the need for a private property. `getRows()` can be changed to suit.

Also, does the table renderer care if the array is a hash or a list? If it doesn't make any difference, you can just always return the hash from `getRows()`, reducing complexity, and drop the `$requireNames` argument

2024-11-20 11:08 UTC, gsteel commented on src/Routes/ListRoutesCommand.php
> +        private RouteFilterOptionsInterface $filterOptions
The `$filterOptions` property is redundant - it's a value object created at runtime from a bunch of strings and it's immediately overwritten when calling `execute`

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/EmptyRouteFilterOptions.php
> +<?php
This class seems entirely uneccessary

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptionsInterface.php
> +declare(strict_types=1);
This interface seems unnecessary

2024-11-20 11:08 UTC, gsteel commented on test/Routes/ListRoutesCommandTest.php
> +        );
Symfony ships a 'CommandTester' which goes along the lines of:

```php
$this->tester = new CommandTester($command);
```

You can then execute the command with a route collector instance that contains an array of actual routes and assert that the table output and json output match expectations rather than mocking everything and asserting a bunch of methods are called.

https://symfony.com/doc/current/console.html#testing-commands

2024-11-20 11:08 UTC, gsteel commented on test/Routes/ListRoutesCommandTest.php
> +        );
If you make the route collector a test property, you can inject routes into it, per test to vary expected output based on options passed to the command and then there's effectively no mocking

2024-11-20 11:08 UTC, gsteel commented on src/Routes/Filter/RouteFilterOptions.php
> +            if (in_array($key, $this->getFilterOptionsMinusMethods()) && $value !== "") {
The entire `toArray()` method is unused in the command AFAICT. Can it be dropped?

2024-11-20 11:13 UTC, froschdesign commented on README.md
> +- _config/routes.php_
> The filename must be enclosed in backticks (`):
> 
> - for a single file: `filename.ext`
> - for a file in a directory: `directory/filename.ext`

2024-12-10 09:42 UTC, settermjd commented
> Sorry @settermjd - I've got quite a lot of feedback here 😬
> 
> Overall, I think a lot of this can be simplified.

Your feedback is **always** appreciated.

2024-12-10 09:49 UTC, settermjd commented on src/Routes/Filter/EmptyRouteFilterOptions.php
> +<?php
The intention was to provide an empty set of options, something more specific than an empty array.

2024-12-10 09:51 UTC, settermjd commented on src/Routes/ListRoutesCommand.php
> +        private RouteFilterOptionsInterface $filterOptions
I see. I missed that before.

2024-12-10 09:58 UTC, settermjd commented on src/Routes/Filter/RouteFilterOptionsInterface.php
> +declare(strict_types=1);
It's still used in `RoutesFilter` and seems worth keeping.

2024-12-10 10:18 UTC, settermjd commented on src/Routes/Filter/RouteFilterOptions.php
> +            if (in_array($key, $this->getFilterOptionsMinusMethods()) && $value !== "") {
It seems to only be used in testing, but not otherwise.

2024-12-10 10:22 UTC, settermjd commented on src/ConfigProvider.php
> +                ConfigLoaderInterface::class                    => DefaultRoutesConfigLoaderFactory::class,
So, it'd look a bit like the following?

```php
return [
    'aliases' => [
        ConfigLoaderInterface::class => RoutesFileConfigLoader::class,
    ],
    'factories' => [
        RoutesFileConfigLoader::class => DefaultRoutesConfigLoaderFactory::class,
    ]
];
```

2024-12-10 10:40 UTC, settermjd commented on test/Routes/ListRoutesCommandTest.php
> +        );
I'll get in to this tomorrow. Feeling a big tired at the moment.

2024-12-17 12:35 UTC, froschdesign commented
@settermjd 
Please check the conflicts.
Thanks in advance! 👍🏻

2024-12-19 04:28 UTC, settermjd commented
@gsteel @froschdesign please let me know if changes are still required.

2025-03-04 17:12 UTC, samsonasik commented on README.md
> +If you don't store any routes in _config/routes.php_ or need a custom implementation, then you need to do two things:
```suggestion
If you don't store any routes in *config/routes.php* or need a custom implementation, then you need to do two things:
```

2025-03-04 17:13 UTC, samsonasik commented on src/ConfigProvider.php
> +            'aliases'   => [
psalm baseline may need to be regerated for this

2025-03-04 19:11 UTC, froschdesign commented on README.md
> +If you don't store any routes in _config/routes.php_ or need a custom implementation, then you need to do two things:
> # Filenames
> 
> A filename must be enclosed in backticks (`).
> 
> ## Basic Usage
> 
> ```markdown
> - for a single file: `filename.ext`
> - for a file in a directory: `directory/filename.ext`
> ```
> 
> ### Output
> 
> - for a single file: `filename.ext`
> - for a file in a directory: `directory/filename.ext`

2025-03-05 00:08 UTC, gsteel commented
@settermjd I've pushed some changes to simplify the implementation and reduce the public api.

Please review and hopefully we can get this out in a patch (possibly)

cc @froschdesign @samsonasik

2025-03-05 01:25 UTC, samsonasik commented
Documentation lint seems still error https://github.com/mezzio/mezzio-tooling/actions/runs/13665425711/job/38205682296?pr=58

2025-03-05 09:19 UTC, samsonasik approved these changes

2025-03-05 09:25 UTC, gsteel commented
@samsonasik Do you think this should be released as a patch? i.e. `2.10.1`

2025-03-05 09:30 UTC, samsonasik commented
2.10.1 is fine for me 👍

2025-03-05 09:37 UTC, merged

2025-03-05 09:44 UTC, froschdesign commented
@gsteel @samsonasik 
The important part is here to inform the end user.
Personally, I would have been in favour of a minor version. (Reference: [semver.org](https://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release))